/**
 * THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE.
 * This is a vitest setup file that creates an isolated test environment.
 * Any changes should be made to the vitest configuration or discussed with the team.
 */
import { beforeAll, afterAll } from "vitest";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

// Create a unique temp directory for this test run
const testTempDir = path.join(os.tmpdir(), `servherd-test-${process.pid}`);

beforeAll(() => {
  // Create the temp directory and .servherd subdirectory
  const servherdDir = path.join(testTempDir, ".servherd");
  fs.mkdirSync(servherdDir, { recursive: true });

  // Set SERVHERD_HOME to redirect all servherd operations to the temp directory
  process.env.SERVHERD_HOME = testTempDir;
});

afterAll(() => {
  // Clean up the temp directory after tests complete
  if (fs.existsSync(testTempDir)) {
    fs.rmSync(testTempDir, { recursive: true, force: true });
  }
});
