#!/usr/bin/env node
// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE
/**
 * This script adds the shebang line to the built CLI entry point.
 * Run this after TypeScript compilation to ensure the CLI is executable.
 *
 * Usage: node scripts/add-shebang.js
 */

import { readFileSync, writeFileSync, chmodSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distPath = join(__dirname, "..", "dist", "index.js");

const SHEBANG = "#!/usr/bin/env node\n";

try {
  // Read the current content
  const content = readFileSync(distPath, "utf-8");

  // Check if shebang already exists
  if (content.startsWith("#!")) {
    console.log("Shebang already present in dist/index.js");
    process.exit(0);
  }

  // Add shebang at the beginning
  const newContent = SHEBANG + content;
  writeFileSync(distPath, newContent, "utf-8");

  // Make the file executable
  chmodSync(distPath, 0o755);

  console.log("Successfully added shebang to dist/index.js");
  console.log("Made dist/index.js executable");
} catch (error) {
  if (error.code === "ENOENT") {
    console.error("Error: dist/index.js not found. Run 'npm run build' first.");
    process.exit(1);
  }
  console.error("Error:", error.message);
  process.exit(1);
}
