// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT src/types/errors.ts
import { describe, it, expect } from "vitest";
import { ServherdError, ServherdErrorCode, isServherdError, formatErrorForCLI, formatErrorForMCP } from "../../src/types/errors.js";

describe("ServherdError", () => {
  describe("constructor", () => {
    it("should create error with code and message", () => {
      const error = new ServherdError(
        ServherdErrorCode.PORT_UNAVAILABLE,
        "Port 3000 is in use",
      );
      expect(error.code).toBe(ServherdErrorCode.PORT_UNAVAILABLE);
      expect(error.message).toBe("Port 3000 is in use");
      expect(error.name).toBe("ServherdError");
    });

    it("should include details when provided", () => {
      const error = new ServherdError(
        ServherdErrorCode.PM2_START_FAILED,
        "Failed to start",
        { exitCode: 1, stderr: "Error output" },
      );
      expect(error.details?.exitCode).toBe(1);
      expect(error.details?.stderr).toBe("Error output");
    });

    it("should be an instance of Error", () => {
      const error = new ServherdError(
        ServherdErrorCode.SERVER_NOT_FOUND,
        "Server not found",
      );
      expect(error).toBeInstanceOf(Error);
    });

    it("should have correct error code values", () => {
      expect(ServherdErrorCode.SERVER_NOT_FOUND).toBe(1001);
      expect(ServherdErrorCode.SERVER_ALREADY_EXISTS).toBe(1002);
      expect(ServherdErrorCode.PORT_UNAVAILABLE).toBe(2001);
      expect(ServherdErrorCode.PORT_OUT_OF_RANGE).toBe(2002);
      expect(ServherdErrorCode.PM2_CONNECTION_FAILED).toBe(3001);
      expect(ServherdErrorCode.PM2_START_FAILED).toBe(3002);
      expect(ServherdErrorCode.PM2_STOP_FAILED).toBe(3003);
      expect(ServherdErrorCode.PM2_DELETE_FAILED).toBe(3004);
      expect(ServherdErrorCode.CONFIG_LOAD_FAILED).toBe(4001);
      expect(ServherdErrorCode.CONFIG_SAVE_FAILED).toBe(4002);
      expect(ServherdErrorCode.CONFIG_INVALID).toBe(4003);
      expect(ServherdErrorCode.REGISTRY_LOAD_FAILED).toBe(5001);
      expect(ServherdErrorCode.REGISTRY_SAVE_FAILED).toBe(5002);
      expect(ServherdErrorCode.TEMPLATE_INVALID).toBe(6001);
      expect(ServherdErrorCode.COMMAND_INVALID).toBe(7001);
      expect(ServherdErrorCode.UNKNOWN_ERROR).toBe(9999);
    });
  });

  describe("toJSON", () => {
    it("should serialize error to JSON", () => {
      const error = new ServherdError(
        ServherdErrorCode.SERVER_NOT_FOUND,
        "Server brave-tiger not found",
      );
      const json = error.toJSON();
      expect(json).toEqual({
        name: "ServherdError",
        code: ServherdErrorCode.SERVER_NOT_FOUND,
        message: "Server brave-tiger not found",
        details: undefined,
      });
    });

    it("should include details in JSON when present", () => {
      const error = new ServherdError(
        ServherdErrorCode.PM2_START_FAILED,
        "Failed to start",
        { exitCode: 1 },
      );
      const json = error.toJSON();
      expect(json.details).toEqual({ exitCode: 1 });
    });
  });
});

describe("isServherdError", () => {
  it("should return true for ServherdError instances", () => {
    const error = new ServherdError(
      ServherdErrorCode.SERVER_NOT_FOUND,
      "Not found",
    );
    expect(isServherdError(error)).toBe(true);
  });

  it("should return false for regular Error instances", () => {
    const error = new Error("Regular error");
    expect(isServherdError(error)).toBe(false);
  });

  it("should return false for non-error values", () => {
    expect(isServherdError(null)).toBe(false);
    expect(isServherdError(undefined)).toBe(false);
    expect(isServherdError("error")).toBe(false);
    expect(isServherdError({ code: 1001 })).toBe(false);
  });
});

describe("formatErrorForCLI", () => {
  it("should format ServherdError with code and message", () => {
    const error = new ServherdError(
      ServherdErrorCode.SERVER_NOT_FOUND,
      "Server brave-tiger not found",
    );
    const formatted = formatErrorForCLI(error);
    expect(formatted).toContain("Error [1001]");
    expect(formatted).toContain("Server brave-tiger not found");
  });

  it("should include details when present", () => {
    const error = new ServherdError(
      ServherdErrorCode.PM2_START_FAILED,
      "Failed to start",
      { stderr: "Some error output" },
    );
    const formatted = formatErrorForCLI(error);
    expect(formatted).toContain("Some error output");
  });

  it("should format regular Error with just message", () => {
    const error = new Error("Regular error message");
    const formatted = formatErrorForCLI(error);
    expect(formatted).toContain("Error:");
    expect(formatted).toContain("Regular error message");
  });

  it("should handle unknown error types", () => {
    const formatted = formatErrorForCLI("string error" as unknown as Error);
    expect(formatted).toContain("Unknown error");
  });

  it("should include stdout details when present", () => {
    const error = new ServherdError(
      ServherdErrorCode.PM2_START_FAILED,
      "Failed to start",
      { stdout: "Some stdout output" },
    );
    const formatted = formatErrorForCLI(error);
    expect(formatted).toContain("Some stdout output");
  });
});

describe("formatErrorForMCP", () => {
  it("should format ServherdError for MCP response", () => {
    const error = new ServherdError(
      ServherdErrorCode.SERVER_NOT_FOUND,
      "Server not found",
    );
    const formatted = formatErrorForMCP(error);
    expect(formatted.isError).toBe(true);
    expect(formatted.content).toHaveLength(1);
    expect(formatted.content[0].type).toBe("text");
    expect(formatted.content[0].text).toContain("SERVER_NOT_FOUND");
    expect(formatted.content[0].text).toContain("Server not found");
  });

  it("should include error code in MCP response", () => {
    const error = new ServherdError(
      ServherdErrorCode.PORT_UNAVAILABLE,
      "Port in use",
    );
    const formatted = formatErrorForMCP(error);
    const parsed = JSON.parse(formatted.content[0].text);
    expect(parsed.code).toBe(ServherdErrorCode.PORT_UNAVAILABLE);
  });

  it("should handle regular Error for MCP response", () => {
    const error = new Error("Regular error");
    const formatted = formatErrorForMCP(error);
    expect(formatted.isError).toBe(true);
    const parsed = JSON.parse(formatted.content[0].text);
    expect(parsed.code).toBe(ServherdErrorCode.UNKNOWN_ERROR);
    expect(parsed.message).toBe("Regular error");
  });

  it("should handle non-Error values for MCP response", () => {
    const formatted = formatErrorForMCP("string error");
    expect(formatted.isError).toBe(true);
    const parsed = JSON.parse(formatted.content[0].text);
    expect(parsed.code).toBe(ServherdErrorCode.UNKNOWN_ERROR);
    expect(parsed.message).toBe("An unknown error occurred");
  });
});
